# Ayoub Sikouky
# Rev. Date: 4/12/2019

import matplotlib.pyplot as plt
from pathlib import Path
import csv

print("\nThis Program will Create a graph from the csv files generated by GameOfLife simulation.")
print("You can enter multiple just separate them by space")
print("You need to close the previous figure to see next figures\n")

# Storing each file name inside a list.
table_files = input("Enter Table files name: ").split()


# Check if the inputs are files, if Not they will be removed.
for t_file in table_files:
    if not Path(t_file).is_file():
        print(f"{t_file} Doesn't exists!!")
        table_files.remove(t_file)


# Checking if the list is empty.
if table_files:
    for file in table_files:
        greenflies = []
        ladybirds = []
        time_steps = []
        with open(file, 'r') as table:
            values = csv.reader(table)
            for row in values:
                if row:
                    time_steps.append(row[0])
                    greenflies.append(row[1])
                    ladybirds.append(row[2])

        ladybirds = [int(i) for i in ladybirds[1:]]
        greenflies = [int(i) for i in greenflies[1:]]
        time_steps = [int(i) for i in time_steps[1:]]

        plt.figure(f"{Path(file).stem}Graph")
        plt.plot(time_steps, greenflies, label='Greenflies')
        plt.plot(time_steps, ladybirds, label='Ladybirds')
        plt.xlim(left=0)
        plt.ylim(bottom=0)
        plt.xlabel("Time Step")
        plt.ylabel("Creatures Number")
        plt.title('Line Graph For Greenflies and Ladybirds population overtime')
        plt.legend()
        plt.grid()
        plt.show()
